// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdTM1xNI1vmvn7nK5ax-WHCnZeWY5ijAw',
    appId: '1:762027198792:web:ad8029d1313242000d0b7d',
    messagingSenderId: '762027198792',
    projectId: 'projetogps1',
    authDomain: 'projetogps1.firebaseapp.com',
    storageBucket: 'projetogps1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Fk6aotkMLlWFddULkRx-hO-1Y-CWUzM',
    appId: '1:762027198792:android:ab141025a1bbff000d0b7d',
    messagingSenderId: '762027198792',
    projectId: 'projetogps1',
    storageBucket: 'projetogps1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSvG19S2o3ZhWikonsnjOGCKZtMrOrUq0',
    appId: '1:762027198792:ios:fa0556a43d6c89c20d0b7d',
    messagingSenderId: '762027198792',
    projectId: 'projetogps1',
    storageBucket: 'projetogps1.appspot.com',
    iosBundleId: 'com.example.projetoGps1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSvG19S2o3ZhWikonsnjOGCKZtMrOrUq0',
    appId: '1:762027198792:ios:fa0556a43d6c89c20d0b7d',
    messagingSenderId: '762027198792',
    projectId: 'projetogps1',
    storageBucket: 'projetogps1.appspot.com',
    iosBundleId: 'com.example.projetoGps1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdTM1xNI1vmvn7nK5ax-WHCnZeWY5ijAw',
    appId: '1:762027198792:web:8981942a7ffe01ff0d0b7d',
    messagingSenderId: '762027198792',
    projectId: 'projetogps1',
    authDomain: 'projetogps1.firebaseapp.com',
    storageBucket: 'projetogps1.appspot.com',
  );
}
